version: "3"
services:
  rss:
    container_name: bot
    build: .
    restart: unless-stopped
    volumes:
      - .:/home/bot
      - /home/bot/node_modules
    environment:
      MONGODB: ${MONGODB}
